name: CI/CD Pipeline - Node.js

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Adicionar host remoto aos conhecidos (known_hosts)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Sincronizar arquivos para o servidor remoto via rsync
        run: |
          rsync -avz ./app/ root@${{ secrets.SERVER_IP }}:/var/www/node-service/app/

      - name: Executar comandos remotos para instalar dependências e reiniciar a aplicação
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/node-service/app
            npm install
            pm2 restart node-service || pm2 start index.js --name "node-service"